---
- tags: [team-overview]
  block:
    - name: Add user for creating the team-overview document
      user:
        name: "{{ team_overview_user }}"
        shell: /bin/bash

    - name: Install pyenv
      import_role: name=pyenv
      vars:
        user: "{{ team_overview_user }}"

    - name: Create base directory
      file:
        path: "{{ base_directory }}"
        state: directory
        owner: "{{ team_overview_user }}"
        group: "{{ team_overview_user }}"
        mode: 0700

    - name: Copy scripts for creating team overview
      template:
        src: "{{ item }}"
        dest: "{{ base_directory }}/{{ item }}"
        owner: "{{ team_overview_user }}"
        group: "{{ team_overview_user }}"
        mode: 0700
      with_items:
        - update_working_directory
        - update_team_overview

    - name: Install nginx
      package: name=nginx state=present
