---
- tags: [team-overview]
  block:
    - name: Add user for creating the team-overview document
      user:
        name: "{{ team_overview_user }}"
        shell: /bin/bash

    - name: Install pyenv
      import_role: name=pyenv
      vars:
        user: "{{ team_overview_user }}"

    - name: Create working directory
      file:
        path: "{{ working_directory }}"
        state: directory
        owner: "{{ team_overview_user }}"
        group: "{{ team_overview_user }}"
        mode: 0700

    - name: Clone repository for creating team-overview
      git:
        repo: https://github.com/serlo-org/serlo-highrise-report.git
        dest: "{{ repository }}"

    - name: Install nginx
      package: name=nginx state=present
