---
- tags: [webserver]
  block:
    - name: Install nginx
      package: name=nginx state=present
      notify: "restart webserver"

    - name: Remove configuration of default webserver
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify: "restart webserver"

    - name: Create web directory
      file:
        path: "{{ webserver_directory }}"
        state: directory
        owner: "{{ webserver_user }}"
        group: "{{ webserver_group }}"
        mode: 0770
        recurse: true

    - name: Start webserver
      service: name=nginx state=started

    - name: Configure server
      template:
        src: nginx_server.conf
        dest: /etc/nginx/sites-enabled/{{ webserver_name }}.conf
      notify: "restart webserver"
