---
- tags: [webserver]
  block:
    - name: Install nginx
      package: name=nginx state=present
      notify: "restart webserver"

    - name: Remove configuration of default webserver
      file: path={{ webserver_sites_enabled }}/default state=absent
      notify: "restart webserver"

    - name: Create directory for webserver configurations
      file:
        path: "{{ webserver_conf_directory }}"
        state: directory
        recurse: true

    - name: Save configuration of webserver
      template:
        src: nginx_server.conf
        dest: "{{ webserver_conf }}"

    - name: Configure webserver
      file:
        src: "{{ webserver_conf }}"
        dest: "{{ webserver_sites_enabled }}/{{ webserver_name }}.conf"
        state: link
      notify: "restart webserver"

    - name: Create web directory
      file:
        path: "{{ webserver_directory }}"
        state: directory
        owner: "{{ webserver_user }}"
        group: "{{ webserver_group }}"
        mode: 0770
        recurse: true

    - name: Start webserver
      service: name=nginx state=started
