---
- tags: [webserver]
  block:
    - name: Install nginx
      package: name=nginx state=present
      notify: "restart webserver"

    - name: Remove configuration of default webserver
      file:
        path: "{{ webserver_sites_enabled }}/default"
        state: absent
      notify: "restart webserver"

    - name: Create directory for webserver configurations
      file:
        path: "{{ webserver_conf_directory }}"
        state: directory
        recurse: true

    - name: Save configuration of webserver
      template:
        src: nginx_server.conf
        dest: "{{ webserver_conf }}"
      notify: "restart webserver"

    - name: Install pyOpenSSL
      package: name=python-openssl state=present

    - name: Generate OpenSSL private key
      openssl_privatekey:
        path: "{{ webserver_ssl_privatekey }}"
        state: present
      notify: "restart webserver"

    - name: Generate OpenSSL CSR
      openssl_csr:
        path: "{{ webserver_ssl_csr }}"
        privatekey_path: "{{ webserver_ssl_privatekey }}"
        common_name: "{{ webserver_name }}"
        state: present
      notify: "restart webserver"

    - name: Generate Self Signed OpenSSL certificate
      openssl_certificate:
        path: "{{ webserver_ssl_certificate }}"
        privatekey_path: "{{ webserver_ssl_privatekey }}"
        csr_path: "{{ webserver_ssl_csr }}"
        provider: selfsigned
        state: present
      notify: "restart webserver"

    - name: Copy auth basic user file for webserver
      copy:
        src: "{{ webserver_passwd_file }}"
        dest: "{{ webserver_auth_basic_user_file }}"
      when: webserver_passwd_file is defined

    - name: Configure webserver
      file:
        src: "{{ webserver_conf }}"
        dest: "{{ webserver_sites_enabled }}/{{ webserver_name }}.conf"
        state: link
      notify: "restart webserver"

    - name: Create web directory
      file:
        path: "{{ webserver_directory }}"
        state: directory
        owner: "{{ webserver_user }}"
        group: "{{ webserver_group }}"
        mode: 0770
        recurse: true

    - name: Start webserver
      service: name=nginx state=started
