---
- tags: [webserver]
  block:
    - name: Install nginx
      package: name=nginx state=present

    - name: Remove configuration of default webserver
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: Create web directory
      file:
        path: "{{ webserver_directory }}"
        state: directory
        owner: "{{ webserver_user }}"
        group: "{{ webserver_group }}"
        mode: 0770
        recurse: true
