---
- tags: [sshd]
  block:
    - name: Configure sshd
      copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
        mode: 0400
      notify: "restart ssh"

    - name: Start sshd
      service: name=sshd state=started
